services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    image: my-fullstack-app-server-prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URL=${MONGODB_URL}

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: my-fullstack-app-client-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server
